import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  AlertTriangle,
  ArrowRight,
  Check,
  Clock3,
  FileCheck2,
  Flame,
  Gauge,
  MapPin,
  PauseCircle,
  Play,
  Radio,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  UserRound,
  Waves,
} from 'lucide-react';
import PageHeader from '../components/ui/PageHeader';
import StatusBadge from '../components/ui/StatusBadge';
import KpiCard from '../components/ui/KpiCard';
import { useSimulation } from '../hooks/useSimulation';

type Permit = {
  id: string;
  type: string;
  activity: string;
  zone: string;
  contractor: string;
  owner: string;
  window: string;
  status: 'draft' | 'active' | 'suspended' | 'closed';
  risk: 'low' | 'medium' | 'high' | 'critical';
};

const permits: Permit[] = [
  { id: 'HW-104', type: 'Hot work', activity: 'Welding support bracket', zone: 'Reactor Bay A', contractor: 'Vega Maintenance', owner: 'Ravi Kumar', window: '09:00–13:00', status: 'active', risk: 'high' },
  { id: 'CS-081', type: 'Confined space', activity: 'Vessel inspection', zone: 'Storage Tank Farm', contractor: 'Nexa Inspection', owner: 'Meera Iyer', window: '10:30–12:30', status: 'active', risk: 'medium' },
  { id: 'EI-219', type: 'Electrical isolation', activity: 'Motor starter replacement', zone: 'Distillation Unit', contractor: 'Plant Electrical', owner: 'Kabir Singh', window: '08:00–16:00', status: 'active', risk: 'low' },
  { id: 'WAH-055', type: 'Work at height', activity: 'Cable tray inspection', zone: 'Cooling Tower', contractor: 'Internal team', owner: 'Nisha Shah', window: '13:00–15:00', status: 'draft', risk: 'low' },
];

const riskByStage = { baseline: 18, permit: 46, rising: 78, critical: 92, response: 96 } as const;
const gasByStage = { baseline: 8, permit: 8, rising: 32, critical: 48, response: 48 } as const;

export default function PermitRiskCenter() {
  const navigate = useNavigate();
  const { stage, setStage } = useSimulation();
  const [selectedId, setSelectedId] = useState('HW-104');
  const [filter, setFilter] = useState<'all' | 'flagged'>('all');

  const selected = permits.find((permit) => permit.id === selectedId) || permits[0];
  const activeRisk = selected.id === 'HW-104' ? riskByStage[stage] : selected.risk === 'medium' ? 58 : 28;
  const activeGas = selected.id === 'HW-104' ? gasByStage[stage] : selected.zone === 'Storage Tank Farm' ? 19 : 11;
  const flaggedCount = permits.filter((permit) => permit.risk === 'high' || permit.risk === 'critical').length;
  const visiblePermits = useMemo(() => filter === 'flagged' ? permits.filter((permit) => permit.risk === 'high' || permit.risk === 'critical') : permits, [filter]);
  const riskLevel = activeRisk >= 90 ? 'critical' : activeRisk >= 70 ? 'high' : activeRisk >= 40 ? 'medium' : 'low';

  return (
    <div className="space-y-6">
      <PageHeader
        title="Permit Risk Center"
        subtitle="Review work permits against current plant conditions before work begins or resumes."
        meta={<div className="flex flex-wrap items-center gap-2"><StatusBadge variant="dot" pulse className="border-amber-500/30 bg-amber-500/10 text-amber-300">Simulation mode</StatusBadge><span className="font-mono text-[11px] text-zinc-500">Digital permit-to-work control</span></div>}
        actions={<button onClick={() => navigate('/risk-intelligence')} className="flex h-9 items-center gap-2 rounded-lg bg-gradient-to-b from-cyan-500 to-sky-600 px-3 text-xs font-semibold text-zinc-950 shadow-lg shadow-cyan-500/10 hover:from-cyan-400 hover:to-sky-500"><Sparkles className="h-3.5 w-3.5" />Open risk simulation</button>}
      />

      <div className="rounded-xl border border-amber-500/25 bg-amber-500/[0.06] px-4 py-3 text-xs text-amber-100/80">
        <div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><p><span className="font-semibold text-amber-200">Demonstration data:</span> permit status and telemetry are generated by the ProtectAI digital plant simulator. Connect a permit system and IoT adapter later without changing this review workflow.</p></div>
      </div>

      <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Active permits" value="3" icon={FileCheck2} tone="cyan" footnote="Current simulated shift" />
        <KpiCard label="Flagged permits" value={flaggedCount} icon={ShieldAlert} tone="red" footnote="Require safety review" />
        <KpiCard label="Nearest sensor" value={selectedId === 'HW-104' ? '35' : '82'} unit="m" icon={MapPin} tone="violet" footnote="Distance to active work" />
        <KpiCard label="Risk lead time" value={stage === 'baseline' ? '—' : stage === 'permit' ? '32' : stage === 'rising' ? '12' : '8'} unit={stage === 'baseline' ? '' : 'min'} icon={Clock3} tone={activeRisk >= 90 ? 'red' : 'amber'} footnote="Before escalation" />
      </div>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-[0.95fr_1.05fr]">
        <section className="surface-glass rounded-xl p-5">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div><p className="text-[10.5px] font-medium uppercase tracking-[0.18em] text-zinc-500">Permit register</p><h2 className="mt-1 text-sm font-semibold text-zinc-100">Work in the plant</h2></div>
            <div className="flex rounded-lg border border-zinc-800 bg-zinc-950/40 p-0.5">
              <button onClick={() => setFilter('all')} className={`rounded-md px-2.5 py-1.5 text-[11px] ${filter === 'all' ? 'bg-zinc-800 text-zinc-100' : 'text-zinc-500'}`}>All</button>
              <button onClick={() => setFilter('flagged')} className={`rounded-md px-2.5 py-1.5 text-[11px] ${filter === 'flagged' ? 'bg-red-500/15 text-red-200' : 'text-zinc-500'}`}>Flagged</button>
            </div>
          </div>
          <div className="mt-4 space-y-2">
            {visiblePermits.map((permit) => {
              const selectedRow = selectedId === permit.id;
              const liveRisk = permit.id === 'HW-104' ? riskByStage[stage] : permit.risk === 'medium' ? 58 : 28;
              return (
                <button key={permit.id} onClick={() => setSelectedId(permit.id)} className={`w-full rounded-lg border p-3 text-left transition-colors ${selectedRow ? 'border-cyan-500/40 bg-cyan-500/[0.06]' : 'border-zinc-800/70 bg-zinc-900/35 hover:border-zinc-700'}`}>
                  <div className="flex items-start gap-3">
                    <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border ${permit.type === 'Hot work' ? 'border-orange-500/30 bg-orange-500/10 text-orange-300' : 'border-zinc-800 bg-zinc-950/60 text-zinc-400'}`}><Flame className="h-4 w-4" /></div>
                    <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] text-cyan-300">{permit.id}</span><span className="text-[10px] text-zinc-600">·</span><span className="text-[10px] text-zinc-500">{permit.type}</span><span className={`rounded-full border px-1.5 py-0.5 text-[9px] uppercase tracking-wider ${riskClasses(liveRisk >= 90 ? 'critical' : liveRisk >= 70 ? 'high' : liveRisk >= 40 ? 'medium' : 'low')}`}>{riskLabel(liveRisk)}</span></div><p className="mt-1 truncate text-xs font-medium text-zinc-200">{permit.activity}</p><p className="mt-1 text-[11px] text-zinc-500">{permit.zone} · {permit.window}</p></div>
                    <span className="font-mono text-xs text-zinc-300">{liveRisk}</span>
                  </div>
                </button>
              );
            })}
          </div>
        </section>

        <section className="surface-glass rounded-xl p-5">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div><p className="text-[10.5px] font-medium uppercase tracking-[0.18em] text-zinc-500">Permit assessment</p><div className="mt-1 flex items-center gap-2"><h2 className="text-sm font-semibold text-zinc-100">{selected.id} · {selected.activity}</h2><StatusBadge variant="outline" className={riskClasses(riskLevel)}>{riskLabel(activeRisk)} risk</StatusBadge></div></div>
            <span className="font-mono text-[10.5px] text-zinc-500">{selected.status === 'active' ? 'ACTIVE' : 'DRAFT'}</span>
          </div>
          <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">
            <Detail label="Zone" value={selected.zone} icon={MapPin} />
            <Detail label="Owner" value={selected.owner} icon={UserRound} />
            <Detail label="Gas sensor" value={`${activeGas} ppm`} icon={Waves} />
            <Detail label="Distance" value={selected.id === 'HW-104' ? '35 m' : '82 m'} icon={Radio} />
          </div>
          <div className="mt-5 rounded-lg border border-zinc-800/70 bg-zinc-950/35 p-4">
            <div className="flex items-center justify-between"><div><p className="text-[10.5px] font-medium uppercase tracking-[0.18em] text-zinc-500">Contextual risk score</p><p className="mt-1 font-mono text-3xl font-semibold text-zinc-50">{activeRisk}<span className="ml-1 text-sm text-zinc-500">/100</span></p></div><Gauge className={`h-6 w-6 ${riskLevel === 'critical' ? 'text-red-300' : riskLevel === 'high' ? 'text-orange-300' : 'text-cyan-300'}`} /></div>
            <div className="mt-3 h-2 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full rounded-full transition-all duration-500 ${riskBar(activeRisk)}`} style={{ width: `${activeRisk}%` }} /></div>
            <p className="mt-3 text-xs leading-relaxed text-zinc-400">{activeRisk >= 70 ? 'The work context and telemetry disagree with a safe permit state. Pause work, repeat the gas test and notify the control room.' : 'Permit can proceed under current simulated conditions, subject to the required evidence checks.'}</p>
          </div>
          <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">
            <Evidence icon={Waves} label="Current gas reading" value={`${activeGas} ppm · GAS-ZB-01`} state={activeGas >= 25 ? 'warning' : 'verified'} />
            <Evidence icon={MapPin} label="Spatial conflict" value={selected.id === 'HW-104' ? 'Within 35 m of work' : 'Outside risk radius'} state={selected.id === 'HW-104' && activeRisk >= 70 ? 'warning' : 'verified'} />
            <Evidence icon={ShieldCheck} label="Historical context" value={selected.id === 'HW-104' ? '3 similar near-misses' : 'No matching events'} state={selected.id === 'HW-104' ? 'warning' : 'verified'} />
            <Evidence icon={FileCheck2} label="Required second gas test" value={activeRisk >= 70 ? 'Evidence missing' : 'Not yet required'} state={activeRisk >= 70 ? 'missing' : 'verified'} />
          </div>
          <div className="mt-5 flex flex-wrap gap-2 border-t border-zinc-800/60 pt-4">
            {stage === 'baseline' && <button onClick={() => setStage('permit')} className="flex items-center gap-2 rounded-lg bg-cyan-500 px-3 py-2 text-xs font-semibold text-zinc-950 hover:bg-cyan-400"><Play className="h-3.5 w-3.5" />Activate HW-104</button>}
            {stage !== 'baseline' && stage !== 'response' && <button onClick={() => setStage('critical')} className="flex items-center gap-2 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs font-semibold text-red-200 hover:bg-red-500/15"><PauseCircle className="h-3.5 w-3.5" />Pause and escalate</button>}
            {stage === 'response' && <div className="flex items-center gap-2 rounded-lg border border-emerald-500/25 bg-emerald-500/[0.06] px-3 py-2 text-xs text-emerald-200"><Check className="h-3.5 w-3.5" />Permit suspended · response active</div>}
            <button onClick={() => navigate('/risk-intelligence')} className="flex items-center gap-2 rounded-lg border border-zinc-800 bg-zinc-900/40 px-3 py-2 text-xs text-zinc-300 hover:bg-zinc-900">View full evidence <ArrowRight className="h-3.5 w-3.5" /></button>
          </div>
        </section>
      </div>

      <section className="surface-glass rounded-xl p-5">
        <div className="flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-violet-300" /><div><p className="text-[10.5px] font-medium uppercase tracking-[0.18em] text-zinc-500">Recommended control logic</p><h2 className="mt-1 text-sm font-semibold text-zinc-100">Why ProtectAI flags this permit</h2></div></div>
        <div className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-3">
          <LogicStep number="01" title="Read current conditions" description="The simulator supplies sensor values and trend direction for the permit zone." />
          <LogicStep number="02" title="Add work context" description="Permit type, activity and location identify potential ignition or exposure conflicts." />
          <LogicStep number="03" title="Recommend a control" description="The result is an explainable action with evidence, not an unexplained black-box score." />
        </div>
      </section>
    </div>
  );
}

function Detail({ label, value, icon: Icon }: { label: string; value: string; icon: typeof MapPin }) {
  return <div className="rounded-lg border border-zinc-800/60 bg-zinc-900/30 p-3"><Icon className="h-3.5 w-3.5 text-zinc-500" /><p className="mt-2 text-[10px] uppercase tracking-wider text-zinc-600">{label}</p><p className="mt-1 truncate text-xs text-zinc-200">{value}</p></div>;
}

function Evidence({ icon: Icon, label, value, state }: { icon: typeof Waves; label: string; value: string; state: 'verified' | 'warning' | 'missing' }) {
  return <div className="flex items-start gap-2.5 rounded-lg border border-zinc-800/60 bg-zinc-900/30 p-3"><Icon className={`mt-0.5 h-3.5 w-3.5 shrink-0 ${state === 'verified' ? 'text-emerald-300' : state === 'warning' ? 'text-amber-300' : 'text-red-300'}`} /><div className="min-w-0"><p className="text-[10.5px] uppercase tracking-wider text-zinc-600">{label}</p><p className="mt-1 text-xs text-zinc-300">{value}</p></div></div>;
}

function LogicStep({ number, title, description }: { number: string; title: string; description: string }) {
  return <div className="rounded-lg border border-zinc-800/60 bg-zinc-900/30 p-4"><span className="font-mono text-[10px] text-cyan-300">{number}</span><p className="mt-2 text-xs font-semibold text-zinc-200">{title}</p><p className="mt-1 text-[11px] leading-relaxed text-zinc-500">{description}</p></div>;
}

function riskLabel(score: number | string) {
  const value = typeof score === 'number' ? score : score === 'critical' ? 95 : score === 'high' ? 78 : score === 'medium' ? 50 : 20;
  return value >= 90 ? 'Critical' : value >= 70 ? 'High' : value >= 40 ? 'Medium' : 'Low';
}

function riskClasses(level: string) {
  const value = level.toLowerCase();
  return value === 'critical' ? 'border-red-500/30 bg-red-500/10 text-red-300' : value === 'high' ? 'border-orange-500/30 bg-orange-500/10 text-orange-300' : value === 'medium' ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300';
}

function riskBar(score: number) {
  return score >= 90 ? 'bg-gradient-to-r from-orange-500 to-red-500' : score >= 70 ? 'bg-gradient-to-r from-amber-400 to-orange-500' : score >= 40 ? 'bg-gradient-to-r from-cyan-400 to-amber-400' : 'bg-gradient-to-r from-cyan-400 to-emerald-400';
}
